### PR TITLE
Update dependencies and test suite

### PR DESCRIPTION
**Pull request by soerenmartius**
Depends on #8 

Ticket https://app.shortcut.com/mineiros/story/6291/update-terraform-google-organization-policy-module

### CODE REVIEW

**Review by waxb — COMMENTED** [review]
Isn't this PR includes https://github.com/mineiros-io/terraform-google-organization-policy/pull/8?

**Comment by soerenmartius** [comment]
> Isn't this PR includes #8?

yip as written in the description, it depends on #8 :)

**Review by mariux — CHANGES_REQUESTED** [review]
blocking till #8 is merged, could you reverse the PRs?

**Comment by soerenmartius** [comment]
> blocking till #8 is merged, could you reverse the PRs?

closed the other PR, deleted the commit in this branch

**Review by mariux — APPROVED** [review]
lgtm

**Pull request merged**
